.dockerignore
.github/workflows/image_build.yml
Dockerfile
build.dockerfile
build.sh

add docker image build workflow

ci: add docker image build workflow

---

src/app/agent/components/TagContent/index.tsx
src/app/agent/components/index.tsx
src/app/agent/components/styles.ts
src/app/agent/page.tsx
src/utils/constants.ts

feat: support agent list api

---

src/app/agent/components/index.tsx
src/app/agent/components/styles.ts

feat: agent list add link to chat page

feat: agent list add link to chat page

---

.github/workflows/image_build.yml
.github/workflows/lint.yml
.npmrc

npm registry change to use http://dev-npm.k8s.com.cn/

chore: change to use k8s.com.cn

---

src/app/[locale]/agent/components/TagContent/index.tsx
src/layout/AppLayout/SideBar/Chats/Item.tsx

fix translate bug: use top level

fix: intl bug: use top level, chat list with locale

---

next.config.mjs
src/app/[locale]/oidc/auth/page.tsx
src/app/[locale]/setting/data-control/page.tsx
src/app/[locale]/setting/user-info/UserInfoClient/index.tsx
src/app/[locale]/setting/user-info/page.tsx
src/layout/AppLayoutWithUser/index.tsx

- remove test code
- GITHUB_SHA || getLastCommitHash()

fix: remove test code

---

src/app/[locale]/chat/bot/create/page.tsx

fix: const type err

---

src/app/[locale]/chat/(conversation)/index.tsx
src/layout/AppLayout/SideBar/Chats/Item.tsx

feat: chat conversion ok

---

src/app/[locale]/agent/components/index.tsx
src/app/[locale]/chat/(conversation)/index.tsx
src/app/[locale]/chat/(conversation)/useDark.tsx
src/layout/AppLayout/SideBar/Chats/index.tsx
src/layout/AppLayout/SideBar/SideBarHeader/index.tsx

feat: gpts new chat

---

package.json
pnpm-lock.yaml
src/app/[locale]/chat/(conversation)/index.tsx

fix: chat undefined issue

---

src/app/[locale]/oidc/layout.tsx
src/app/[locale]/oidc/logout/page.tsx
src/app/[locale]/setting/data-control/DataControlClient/index.tsx
src/app/[locale]/setting/data-control/page.tsx
src/app/[locale]/setting/user-info/page.tsx
src/app/[locale]/test/styles.ts
src/layout/AppLayout/SideBar/Chats/index.tsx
src/layout/AppLayout/SideBar/SideBarHeader/styles.ts
src/layout/AppNoAuthLayout/SideBar/Chats/Item.tsx
src/layout/AppNoAuthLayout/SideBar/SideBarHeader/styles.ts
src/layout/AppSkeletonLayout/SideBar/SideBarHeader/styles.ts
src/theme/themeConfig.ts

fix: optimize layout

---

.npmrc
package.json
pnpm-lock.yaml

chore: bump @yuntijs/chat@0.1.0-beta.7

---

src/layout/GlobalLayout/ThemeLayout/index.tsx
src/utils/client.ts

fix: auth warn

---

package.json
pnpm-lock.yaml

chore: bump @yuntijs/chat@0.1.0-beta.8

---

src/middleware.ts
src/utils/constants.ts

fix: set lang based on system

---

src/app/[locale]/agent/components/TagContent/index.tsx

fix: 修复 TagContent 组件在移动端下表现异常

---

src/app/[locale]/agent/components/TagContent/index.tsx
src/app/[locale]/agent/components/index.tsx
src/app/[locale]/agent/page.tsx
src/layout/AppLayout/SideBar/Chats/index.tsx
src/layout/AppLayout/SideBar/Chats/styles.ts
src/layout/AppLayout/SideBar/index.tsx
src/layout/AppLayout/SideBar/styles.ts
src/layout/AppNoAuthLayout/SideBar/index.tsx
src/layout/AppNoAuthLayout/SideBar/styles.ts
src/layout/AppSkeletonLayout/SideBar/index.tsx
src/layout/AppSkeletonLayout/SideBar/styles.ts
src/utils/constants.ts

fix: categories with intl, chat list action bug

---

src/app/[locale]/agent/components/index.tsx
src/layout/AppNoAuthLayout/SideBar/UserInfoBottom.tsx

fix: no auth chats-bottom => login btn

---

server.mjs
src/app/[locale]/agent/components/index.tsx
src/app/[locale]/agent/components/styles.ts
src/app/[locale]/chat/bot/create/page.tsx
src/app/[locale]/chat/bot/create/styles.ts
src/app/[locale]/setting/user-info/UserInfoClient/index.tsx
src/app/[locale]/setting/user-info/UserInfoClient/styles.ts
src/layout/AppLayout/SideBar/Chats/Item.tsx
src/layout/AppLayout/SideBar/Chats/index.tsx
src/layout/AppLayout/SideBar/SideBarHeader/index.tsx
src/layout/AppSkeletonLayout/SideBar/SideBarHeader/index.tsx

fix: chats in high resolution
- 处理高分辨率下 chat list 加载问题
- img => next/image
- /chat/bot/create 临时改为 /agent #69 
- 未验证auth 显示空, 通过验证显示创建智能体按钮, 未通过显示登录按钮, #70
ref: #69, fix: #70

fix: chats in high resolution

---

src/app/[locale]/oidc/layout.tsx
src/theme/themeConfig.ts

fix: dark-theme use darkAlgorithm

---

package.json
pnpm-lock.yaml
src/app/[locale]/agent/components/TagContent/index.tsx
src/app/[locale]/agent/components/TagContent/styles.ts
src/app/[locale]/agent/components/index.tsx
src/app/[locale]/agent/page.tsx

refactor(Agent): adjust agent category and style

refactor(Agent): adjust agent category and style

---

src/app/[locale]/agent/components/TagContent/index.tsx

fix(Agent): remove using window before mounting

fix(Agent): remove using window before mounting

---

package.json
pnpm-lock.yaml

feat: bump @yuntijs/chat@0.1.0-beta.11

---

package.json
pnpm-lock.yaml

chore: bump @yuntijs/chat@0.1.0-beta.12

---

package.json
pnpm-lock.yaml

chore: bump @yuntijs/chat@0.1.0-beta.13
